### ISSUE TITLE
How to setup the database 

### ISSUE THREAD

**Issue by pitpit** [onefinestay/adyen-notification-proxy#3]
It seems the database is not initialized automaticaly. Is there a command to do it ?

I found this : https://github.com/onefinestay/adyen-notification-proxy/blob/master/adyen_notification_proxy/management.py#L51 but I don't know how to use it...

**Comment by davidszotten** [comment]
looks like you want something like

`DB_URI='/path/to/db.sqlite' python adyen_notification_proxy/management.py --setup`

**Comment by pitpit** [comment]
it works, thanks !
